/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static java.lang.System.exit;

/**
 *
 * @author asus
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listProduitBtn = new javax.swing.JToggleButton();
        listFournisseurBtn = new javax.swing.JToggleButton();
        listClientsBtn = new javax.swing.JToggleButton();
        nvFournisseurBtn = new javax.swing.JToggleButton();
        nvProduitBtn = new javax.swing.JToggleButton();
        nvClientBtn = new javax.swing.JToggleButton();
        nvCommandeBtn = new javax.swing.JToggleButton();
        StockBasBtn = new javax.swing.JToggleButton();
        aRealiserBtn = new javax.swing.JToggleButton();
        dejaRealiserBtn = new javax.swing.JToggleButton();
        ProduitEntres = new javax.swing.JToggleButton();
        produitsSortis = new javax.swing.JToggleButton();
        changePwdBtn = new javax.swing.JButton();
        userListBtn = new javax.swing.JButton();
        newUserBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fournisseurImage = new javax.swing.JLabel();
        produitImage = new javax.swing.JLabel();
        fournisseurImage2 = new javax.swing.JLabel();
        fournisseurImage3 = new javax.swing.JLabel();
        fournisseurImage4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        listProduitBtn.setBackground(new java.awt.Color(0, 0, 0));
        listProduitBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        listProduitBtn.setForeground(new java.awt.Color(255, 255, 255));
        listProduitBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\list.png")); // NOI18N
        listProduitBtn.setText("Consultation des produits");
        listProduitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listProduitBtnActionPerformed(evt);
            }
        });

        listFournisseurBtn.setBackground(new java.awt.Color(0, 0, 0));
        listFournisseurBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        listFournisseurBtn.setForeground(new java.awt.Color(255, 255, 255));
        listFournisseurBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\list.png")); // NOI18N
        listFournisseurBtn.setText("Liste des Fournisseurs");
        listFournisseurBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listFournisseurBtnActionPerformed(evt);
            }
        });

        listClientsBtn.setBackground(new java.awt.Color(0, 0, 0));
        listClientsBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        listClientsBtn.setForeground(new java.awt.Color(255, 255, 255));
        listClientsBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\list.png")); // NOI18N
        listClientsBtn.setText("Liste des Clients");
        listClientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClientsBtnActionPerformed(evt);
            }
        });

        nvFournisseurBtn.setBackground(new java.awt.Color(0, 0, 0));
        nvFournisseurBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        nvFournisseurBtn.setForeground(new java.awt.Color(255, 255, 255));
        nvFournisseurBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\add.png")); // NOI18N
        nvFournisseurBtn.setText("Nouveau fournisseur");
        nvFournisseurBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvFournisseurBtnActionPerformed(evt);
            }
        });

        nvProduitBtn.setBackground(new java.awt.Color(0, 0, 0));
        nvProduitBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        nvProduitBtn.setForeground(new java.awt.Color(255, 255, 255));
        nvProduitBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\add.png")); // NOI18N
        nvProduitBtn.setText("Nouveau produit");
        nvProduitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvProduitBtnActionPerformed(evt);
            }
        });

        nvClientBtn.setBackground(new java.awt.Color(0, 0, 0));
        nvClientBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        nvClientBtn.setForeground(new java.awt.Color(255, 255, 255));
        nvClientBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\add.png")); // NOI18N
        nvClientBtn.setText("Nouveau client");
        nvClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvClientBtnActionPerformed(evt);
            }
        });

        nvCommandeBtn.setBackground(new java.awt.Color(0, 0, 0));
        nvCommandeBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        nvCommandeBtn.setForeground(new java.awt.Color(255, 255, 255));
        nvCommandeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\add.png")); // NOI18N
        nvCommandeBtn.setText("Nouvelle commande");
        nvCommandeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvCommandeBtnActionPerformed(evt);
            }
        });

        StockBasBtn.setBackground(new java.awt.Color(204, 0, 0));
        StockBasBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        StockBasBtn.setForeground(new java.awt.Color(255, 255, 255));
        StockBasBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\warning.png")); // NOI18N
        StockBasBtn.setText("Liste des produits dont le stock est trop bas");
        StockBasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockBasBtnActionPerformed(evt);
            }
        });

        aRealiserBtn.setBackground(new java.awt.Color(0, 0, 0));
        aRealiserBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        aRealiserBtn.setForeground(new java.awt.Color(255, 255, 255));
        aRealiserBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\list.png")); // NOI18N
        aRealiserBtn.setText("Commandes a realiser");
        aRealiserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aRealiserBtnActionPerformed(evt);
            }
        });

        dejaRealiserBtn.setBackground(new java.awt.Color(0, 0, 0));
        dejaRealiserBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        dejaRealiserBtn.setForeground(new java.awt.Color(255, 255, 255));
        dejaRealiserBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\list.png")); // NOI18N
        dejaRealiserBtn.setText("Liste des commandes déjà réalisées");
        dejaRealiserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dejaRealiserBtnActionPerformed(evt);
            }
        });

        ProduitEntres.setBackground(new java.awt.Color(0, 0, 0));
        ProduitEntres.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        ProduitEntres.setForeground(new java.awt.Color(255, 255, 255));
        ProduitEntres.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\list.png")); // NOI18N
        ProduitEntres.setText("Produits Entres");
        ProduitEntres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProduitEntresActionPerformed(evt);
            }
        });

        produitsSortis.setBackground(new java.awt.Color(0, 0, 0));
        produitsSortis.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        produitsSortis.setForeground(new java.awt.Color(255, 255, 255));
        produitsSortis.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\list.png")); // NOI18N
        produitsSortis.setText("Produits Sortis");
        produitsSortis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produitsSortisActionPerformed(evt);
            }
        });

        changePwdBtn.setBackground(new java.awt.Color(0, 0, 0));
        changePwdBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        changePwdBtn.setForeground(new java.awt.Color(255, 255, 255));
        changePwdBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\icon-key.png")); // NOI18N
        changePwdBtn.setText("Changer le mot de passe");
        changePwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePwdBtnActionPerformed(evt);
            }
        });

        userListBtn.setBackground(new java.awt.Color(0, 0, 0));
        userListBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        userListBtn.setForeground(new java.awt.Color(255, 255, 255));
        userListBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\list.png")); // NOI18N
        userListBtn.setText("Listes des comptes d'utilisateurs");
        userListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userListBtnActionPerformed(evt);
            }
        });

        newUserBtn.setBackground(new java.awt.Color(0, 0, 0));
        newUserBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        newUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        newUserBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\add.png")); // NOI18N
        newUserBtn.setText("Creer un nouveau utilisateur");
        newUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestion du Stock");

        fournisseurImage.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        fournisseurImage.setForeground(new java.awt.Color(0, 0, 0));
        fournisseurImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\fournisseur_icon.png")); // NOI18N
        fournisseurImage.setText("Fournisseur");

        produitImage.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        produitImage.setForeground(new java.awt.Color(0, 0, 0));
        produitImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\product_icon.png")); // NOI18N
        produitImage.setText("Produit");

        fournisseurImage2.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        fournisseurImage2.setForeground(new java.awt.Color(0, 0, 0));
        fournisseurImage2.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\client_icon.png")); // NOI18N
        fournisseurImage2.setText("Client");

        fournisseurImage3.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        fournisseurImage3.setForeground(new java.awt.Color(0, 0, 0));
        fournisseurImage3.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\commande_icon.png")); // NOI18N
        fournisseurImage3.setText("Commande");

        fournisseurImage4.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        fournisseurImage4.setForeground(new java.awt.Color(0, 0, 0));
        fournisseurImage4.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\user_icon.png")); // NOI18N
        fournisseurImage4.setText("Utilisateurs");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\16 ou 32\\add.png")); // NOI18N
        jButton1.setText("Nouvelle Transaction");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\logout.png")); // NOI18N
        jButton2.setText("Se Deconnecter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\GestionStock\\images\\fermer.jpg")); // NOI18N
        jButton3.setText("Fermer l'application");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(532, 532, 532)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nvFournisseurBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fournisseurImage, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listFournisseurBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(produitImage, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(fournisseurImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(fournisseurImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StockBasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nvProduitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(produitsSortis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(listProduitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ProduitEntres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(27, 27, 27)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nvClientBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listClientsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nvCommandeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dejaRealiserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(aRealiserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changePwdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(fournisseurImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(191, 191, 191))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fournisseurImage)
                    .addComponent(produitImage)
                    .addComponent(fournisseurImage2)
                    .addComponent(fournisseurImage3)
                    .addComponent(fournisseurImage4))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(newUserBtn)
                                        .addGap(27, 27, 27)
                                        .addComponent(userListBtn)
                                        .addGap(27, 27, 27)
                                        .addComponent(changePwdBtn))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nvCommandeBtn)
                                        .addGap(27, 27, 27)
                                        .addComponent(dejaRealiserBtn)
                                        .addGap(30, 30, 30)
                                        .addComponent(aRealiserBtn))
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nvFournisseurBtn)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nvProduitBtn)
                                        .addComponent(nvClientBtn)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(listProduitBtn)
                                            .addComponent(listClientsBtn)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(listFournisseurBtn)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(produitsSortis)
                                .addGap(18, 18, 18)
                                .addComponent(ProduitEntres)
                                .addGap(18, 18, 18)
                                .addComponent(StockBasBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(13, 13, 13))))
                    .addComponent(jSeparator4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listProduitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listProduitBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ConsultationArticle().setVisible(true);
    }//GEN-LAST:event_listProduitBtnActionPerformed

    private void nvFournisseurBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvFournisseurBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FournisseurCreation().setVisible(true);

    }//GEN-LAST:event_nvFournisseurBtnActionPerformed

    private void nvProduitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvProduitBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ArticleCreation().setVisible(true);

    }//GEN-LAST:event_nvProduitBtnActionPerformed

    private void nvClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvClientBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ClientCreation().setVisible(true);
    }//GEN-LAST:event_nvClientBtnActionPerformed

    private void nvCommandeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvCommandeBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CommandeCreation().setVisible(true);
    }//GEN-LAST:event_nvCommandeBtnActionPerformed

    private void listFournisseurBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listFournisseurBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FournisseursList().setVisible(true);
    }//GEN-LAST:event_listFournisseurBtnActionPerformed

    private void listClientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClientsBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ClientsList().setVisible(true);
    }//GEN-LAST:event_listClientsBtnActionPerformed

    private void StockBasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockBasBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StockBas().setVisible(true);
    }//GEN-LAST:event_StockBasBtnActionPerformed

    private void ProduitEntresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProduitEntresActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Entrees().setVisible(true);
    }//GEN-LAST:event_ProduitEntresActionPerformed

    private void produitsSortisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produitsSortisActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Sorties().setVisible(true);
    }//GEN-LAST:event_produitsSortisActionPerformed

    private void aRealiserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aRealiserBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CommandeArealiser().setVisible(true);
    }//GEN-LAST:event_aRealiserBtnActionPerformed

    private void dejaRealiserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dejaRealiserBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CommandeDejaRealisees().setVisible(true);
    }//GEN-LAST:event_dejaRealiserBtnActionPerformed

    private void changePwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePwdBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ChangePassword().setVisible(true);
    }//GEN-LAST:event_changePwdBtnActionPerformed

    private void newUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UserCreation().setVisible(true);
    }//GEN-LAST:event_newUserBtnActionPerformed

    private void userListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userListBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UsersList().setVisible(true);
    }//GEN-LAST:event_userListBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Transaction().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Connexion().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ProduitEntres;
    private javax.swing.JToggleButton StockBasBtn;
    private javax.swing.JToggleButton aRealiserBtn;
    private javax.swing.JButton changePwdBtn;
    private javax.swing.JToggleButton dejaRealiserBtn;
    private javax.swing.JLabel fournisseurImage;
    private javax.swing.JLabel fournisseurImage2;
    private javax.swing.JLabel fournisseurImage3;
    private javax.swing.JLabel fournisseurImage4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToggleButton listClientsBtn;
    private javax.swing.JToggleButton listFournisseurBtn;
    private javax.swing.JToggleButton listProduitBtn;
    private javax.swing.JButton newUserBtn;
    private javax.swing.JToggleButton nvClientBtn;
    private javax.swing.JToggleButton nvCommandeBtn;
    private javax.swing.JToggleButton nvFournisseurBtn;
    private javax.swing.JToggleButton nvProduitBtn;
    private javax.swing.JLabel produitImage;
    private javax.swing.JToggleButton produitsSortis;
    private javax.swing.JButton userListBtn;
    // End of variables declaration//GEN-END:variables
}
