/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Article;
import bean.Entree;
import bean.Fournisseur;
import bean.Sortie;
import java.util.Date;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import service.ArticleService;
import service.EntreeService;
import service.SortieService;

/**
 *
 * @author asus
 */
public class Transaction extends javax.swing.JFrame {

    ArticleService articleService = new ArticleService();
    EntreeService entreeService = new EntreeService();
    SortieService sortieService = new SortieService();

    private void initArticleCombobox() throws Exception {
        articleBox.removeAllItems();
        articleBox.addItem("--SELECT FOURNISSEURS--");
        List<Article> articles = articleService.findAll();
        for (Article article : articles) {
            articleBox.addItem(article.getId());
        }

    }

    private void initView() throws Exception {
        initArticleCombobox();
    }

    private void initButtons() {
        buttonGroup1.add(EntreeRadioButton);
        buttonGroup1.add(SortirRadioButton);
    }

    /**
     * Creates new form Transaction
     */
    public Transaction() {
        initComponents();
        initButtons();
        try {
            initView();
        } catch (Exception ex) {
            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        quantitetxt = new javax.swing.JTextField();
        prixtxt = new javax.swing.JTextField();
        employetxt = new javax.swing.JTextField();
        articleBox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        EntreeRadioButton = new javax.swing.JRadioButton();
        SortirRadioButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Entrer et Sortir les marchandises du Stock");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("ARTICLE ID");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("QUANTITE");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("PRIX UNITAIRE");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setText("DATE");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setText("EMPLOYE");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setText("ACTIVITE");

        quantitetxt.setBackground(new java.awt.Color(0, 0, 0));
        quantitetxt.setForeground(new java.awt.Color(255, 255, 255));
        quantitetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitetxtActionPerformed(evt);
            }
        });

        prixtxt.setBackground(new java.awt.Color(0, 0, 0));
        prixtxt.setForeground(new java.awt.Color(255, 255, 255));

        employetxt.setBackground(new java.awt.Color(0, 0, 0));
        employetxt.setForeground(new java.awt.Color(255, 255, 255));

        articleBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articleBoxActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Executer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        EntreeRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        EntreeRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        EntreeRadioButton.setText("Entrer");
        EntreeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreeRadioButtonActionPerformed(evt);
            }
        });

        SortirRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        SortirRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        SortirRadioButton.setText("Sortir");
        SortirRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortirRadioButtonActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Retourner");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(126, 126, 126)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(EntreeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SortirRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(prixtxt)
                            .addComponent(quantitetxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(employetxt)
                            .addComponent(articleBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton2)
                        .addGap(26, 26, 26)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(articleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantitetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prixtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntreeRadioButton)
                    .addComponent(SortirRadioButton)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantitetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitetxtActionPerformed

    private void EntreeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntreeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntreeRadioButtonActionPerformed

    private void SortirRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortirRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SortirRadioButtonActionPerformed

    public Sortie getParamSortie() {
        Sortie mySortie = new Sortie();
        mySortie.getArticle().setId(articleBox.getSelectedItem() + "");
        mySortie.setQuantite(new Long(quantitetxt.getText()));
        mySortie.setPrixVente(new Long(prixtxt.getText()));
//        mySortie.setDateSortie(datetxt.getText());
        mySortie.setDateSortie(((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText());
        mySortie.setEmploye(employetxt.getText());
        return mySortie;
    }

    public Entree getParamEntree() {
        Entree myEntree = new Entree();
        myEntree.getArticle().setId(articleBox.getSelectedItem() + "");
        myEntree.setQuantite(new Long(quantitetxt.getText()));
        myEntree.setPrixVente(new Long(prixtxt.getText()));
//        myEntree.setDateEntree(datetxt.getText());
        myEntree.setDateEntree(((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText());
        myEntree.setEmploye(employetxt.getText());
        return myEntree;
    }

    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Sortie mySortie = getParamSortie();
        Entree myEntree = getParamEntree();
        String selectedButton = getSelectedButtonText(buttonGroup1);
        if (selectedButton.equals("Entrer")) {
            System.out.println(selectedButton);
            System.out.println(myEntree.toString());
            try {
                Article loadedArticle = articleService.findById(mySortie.getArticle().getId());
                int res = entreeService.save(myEntree);
                loadedArticle.setQuantite(loadedArticle.getQuantite() + myEntree.getQuantite());
                articleService.update(loadedArticle);

                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "INSCRIPTION AVEC SUCCES", "info", JOptionPane.INFORMATION_MESSAGE);

                    this.setVisible(false);
                    new Accueil().setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, "LA CONFIRMATION DU MOT DE PASSE EST INCORECTTE", "ereur", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "INSCRIPTION AVEC ERROR", "ereur", JOptionPane.ERROR_MESSAGE);
            }

        } else if (selectedButton.equals("Sortir")) {
            System.out.println(selectedButton);
            System.out.println(mySortie.toString());

            try {
                Article loadedArticle = articleService.findById(mySortie.getArticle().getId());
                if (mySortie.getQuantite() > loadedArticle.getQuantite()) {
                    JOptionPane.showMessageDialog(null, "La quantite demandee est superieur a celle du stock", "ereur", JOptionPane.ERROR_MESSAGE);
                } else if (loadedArticle.getQuantite() < 5) {
                    JOptionPane.showMessageDialog(null, "Il n'y a pas suffisament dans le stock", "ereur", JOptionPane.ERROR_MESSAGE);

                } else {
                    int res = sortieService.save(mySortie);
                    loadedArticle.setQuantite(loadedArticle.getQuantite() - mySortie.getQuantite());
                    articleService.update(loadedArticle);
                    if (res > 0) {
                        JOptionPane.showMessageDialog(null, "INSCRIPTION AVEC SUCCES", "info", JOptionPane.INFORMATION_MESSAGE);
                        this.setVisible(false);
                        new Accueil().setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "LA CONFIRMATION DU MOT DE PASSE EST INCORECTTE", "ereur", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "INSCRIPTION AVEC ERROR", "ereur", JOptionPane.ERROR_MESSAGE);

            }

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void articleBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articleBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_articleBoxActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Accueil().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton EntreeRadioButton;
    private javax.swing.JRadioButton SortirRadioButton;
    private javax.swing.JComboBox articleBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField employetxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField prixtxt;
    private javax.swing.JTextField quantitetxt;
    // End of variables declaration//GEN-END:variables
}
